name: Fail

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  failing_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node test_failed.js
