name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  error_cancel:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node test_add.js
  success:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node 20 Success
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: node test_add.js
